### ISSUE TITLE
ICNet Problem

### ISSUE THREAD

**Issue by erichhhhho** [lxtGH/Fast_Seg#1]
In the low-res branch, the input of the low-res feature map(x_sub4) in your code is from the medium and downsample by 0.2. 

But from the original paper, it should be downsampled from the raw input by 0.25, is it?

**Comment by lxtGH** [comment]
No, the original code is a litttle different from the figure in the paper. See this issue https://github.com/hszhao/ICNet/issues/7.

**Comment by erichhhhho** [comment]
@lxtGH Yes. I also noticed that the original code use element-wise summation instead of the concatenation. Would you mind sharing your trained model performance?

**Comment by lxtGH** [comment]
I will report the results and trained model as soon as possible.

**Comment by lxtGH** [comment]
Please use the lastest code for reproducing ICnet results.

**Comment by erichhhhho** [comment]
@lxtGH Thank you.
I think the [ICNet loss](https://github.com/lxtGH/Fast_Seg/blob/master/libs/core/loss.py#L99-127) in your code is inaccurate. 

When you calculate the loss, according to the paper: the ground truth should be downsampled to the prediction size in 1/4, 1/8, 1/16 branch, instead of upsampling the sub prediction. There is a difference. And I was wondering the mIoU in your trained model is reported in the test set or val set?

**Comment by lxtGH** [comment]
You can have try by not upsampling. and I report the results on val set
