### ISSUE TITLE
variable names in pretrained model xceptiona_imagenet.pth  cannot match name in xception.py; maybe a wrong pretrained model?

### ISSUE THREAD

**Issue by liuxiAaoyu** [lxtGH/Fast_Seg#11]

**Comment by liuxiAaoyu** [comment]
I found that variables  name in  pretrained model  xceptiona_imagenet.pth just like this:
".weight .bias .running_mean .running_var .num_batches_tracked ock.0.skip.weight ock.0.skipbn.weight ..."

**Comment by lxtGH** [comment]
pretrained xception weights may be not usefull than seting training time longer.

**Comment by lxtGH** [comment]
You can load the model with strict == False. Also I found xception weights may be not usefull than seting training time longer.
