### ISSUE TITLE
Pan baidu is not accessible 

### ISSUE THREAD

**Issue by w-kok** [lxtGH/Fast_Seg#12]
Pan baidu is not accessible in the EU.
Could you host somewhere else or send me the files?
https://pan.baidu.com/s/1mM_Lc44iX9CT1nPq6tjOAA#list/path=%2F

**Comment by lxtGH** [comment]
I will upload the model weights in Google Drive soon.

**Comment by lxtGH** [comment]
@w-kok  Hi the links has been updated. You can have a try.
