### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'ReduceOp'

### ISSUE THREAD

**Issue by RickXiang** [lxtGH/Fast_Seg#2]
Hello,when I run the train_distribute.py,I had a AttributeError: module 'torch.distributed' has no attribute 'ReduceOp'.How can I fix it?
How many GPU should it have to train this?

**Comment by lxtGH** [comment]
4 GPU and I use torch 1.1.0

**Comment by RickXiang** [comment]
Thx ! Can i just use 1 or 2 GPU to train this?

**Comment by lxtGH** [comment]
You can use 2 GPU not 1GPU and it only support the distributed training now
