### ISSUE TITLE
hi, does the project in building? custom data training

### ISSUE THREAD

**Issue by zhangyunming** [lxtGH/Fast_Seg#3]
hi, it is a good joob that i have wait for several days. i have some questiones.

1. when i use my own data include two class with the lables 0 and 1, how to rewirite below in libs/datasets/cityscapes.py
 self.id_to_trainid = {-1: ignore_label, 0: ignore_label, 1: ignore_label, 2: ignore_label,
                              3: ignore_label, 4: ignore_label, 5: ignore_label, 6: ignore_label,
                              7: 0, 8: 1, 9: ignore_label, 10: ignore_label, 11: 2, 12: 3, 13: 4,
                              14: ignore_label, 15: ignore_label, 16: ignore_label, 17: 5,
                              18: ignore_label, 19: 6, 20: 7, 21: 8, 22: 9, 23: 10, 24: 11, 25: 12, 26: 13, 27: 14,
                              28: 15, 29: ignore_label, 30: ignore_label, 31: 16, 32: 17, 33: 18}

2, the project is still building? msfnet ? fast scnn?
3. can you give a script to support single gpu trainning?
4. the param "arch" is something strange.
5. "You can download pretrained XceptionA here"  the address is none.

**Comment by lxtGH** [comment]
Hi! @zhangyunming 
Sorry for late reply.
1.  the same as the id_to_trainid.
2.  yes, I am still building this project.
3. remove code that related to the apex library.
4.  arch is used to choose the model. 
5. I have upload the pretrained model.
