### ISSUE TITLE
Cannot open the link of ResNet50 model

### ISSUE THREAD

**Issue by Emilycs09** [lxtGH/Fast_Seg#4]
Hi,

Thanks for sharing.

The link to the Resnet50 model is unavailable now, could you provide a new link?

Need the pretrained model for ICNet training.

**Comment by TrevoLan77** [comment]
me too, thanks.

**Comment by lxtGH** [comment]
Hi! guys @Emilycs09 @TrevoLan77  I have upload the ImageNet pretrained models
