### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zpge** [lxtGH/Fast_Seg#7]
这个repo的用意很好，集成可以达到实时的分割网络，而且已经集成了很多模型了，工作量不小。但是为了更好地推广，我觉得当务之急是如何更方便地让别人使用，而不是集成更多的模型。作者可以考虑完善一下使用方法之类的。

**Comment by lxtGH** [comment]
I will add more doc and refactor the code

**Comment by zpge** [comment]
> I will add more doc and refactor the code

Thanks.

**Comment by lxtGH** [comment]
@zpge Do you have any suggestion on refactoring this code base?

**Comment by zpge** [comment]
> @zpge Do you have any suggestion on refactoring this code base?

Have you actually implemented Multiply Spatial Fusion Network?
